### ISSUE TITLE
Can only run one scan at a time or else get an error

### ISSUE THREAD

**Issue by ricochetbrown** [SonarSource/sonar-scanner-npm#109]
I use Nx and would like to use distributed execution of the scanner. Instead I have to run --parellel=1 because sonar-scanner cannot handle multiple instances. This is the error I get:

	... 60 more
Caused by: java.lang.IllegalStateException: Failed to create temp directory
	at org.sonar.api.impl.utils.DefaultTempFolder.createTempDir(DefaultTempFolder.java:62)
	at org.sonar.api.impl.utils.DefaultTempFolder.newDir(DefaultTempFolder.java:55)
	at org.sonar.go.plugin.InstanceScopeGoConverter.<init>(InstanceScopeGoConverter.java:32)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	... 62 more
Caused by: java.nio.file.NoSuchFileException: /home/vsts/work/1/s/.scannerwork/.sonartmp/8791900543638969355
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectory(Unknown Source)
	at java.base/java.nio.file.TempFileHelper.create(Unknown Source)
	at java.base/java.nio.file.TempFileHelper.createTempDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createTempDirectory(Unknown Source)
	at org.sonar.api.impl.utils.DefaultTempFolder.createTempDir(DefaultTempFolder.java:60)
	... 70 more
ERROR: 
The SonarQube scan failed for project '[projectName]'
Error: Command failed: /home/vsts/.sonar/native-sonar-scanner/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner --from=ScannerNpm/3.3.0
    at checkExecSyncError (node:child_process:890:11)
    at execFileSync (node:child_process:926:15)
    at scan (/home/vsts/work/1/s/node_modules/sonarqube-scanner/src/index.js:40:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports.async (/home/vsts/work/1/s/node_modules/sonarqube-scanner/src/index.js:60:3)

**Comment by ilia-kebets-sonarsource** [comment]
Hello,

Are you trying to run multiple analyses in parallel on a single project?

**Comment by ilia-kebets-sonarsource** [comment]
closing as there is no answer. Please make a post in community if the issue persists. FYI, we are migrating the GitHub issues to Jira: https://sonarsource.atlassian.net/jira/software/c/projects/SCANNPM/issues
