### ISSUE TITLE
SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by marco-carvalho** [SonarSource/sonar-scanner-npm#31]
Since last week I'm getting this. Any help please?

```
11:44:57   npx: installed 62 in 9.725s
11:44:58   /home/buildagent/.npm/_npx/6488/lib/node_modules/sonarqube-scanner/src/sonar-scanner-params.js:152
11:44:58       if (pkg.bugs?.url) {
11:44:58                    ^
11:44:58   
11:44:58   SyntaxError: Unexpected token .
11:44:58       at Module._compile (internal/modules/cjs/loader.js:723:23)
11:44:58       at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
11:44:58       at Module.load (internal/modules/cjs/loader.js:653:32)
11:44:58       at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
11:44:58       at Function.Module._load (internal/modules/cjs/loader.js:585:3)
11:44:58       at Module.require (internal/modules/cjs/loader.js:692:17)
11:44:58       at require (internal/modules/cjs/helpers.js:25:18)
11:44:58       at Object.<anonymous> (/home/buildagent/.npm/_npx/6488/lib/node_modules/sonarqube-scanner/src/config.js:20:28)
11:44:58       at Module._compile (internal/modules/cjs/loader.js:778:30)
11:44:58       at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
11:44:59   Process exited with code 1
11:44:59   Process exited with code 1 (Step: Sonarqube (Command Line))
11:44:59   Step Sonarqube (Command Line) failed
```

**Comment by marco-carvalho** [comment]
I've rollback to 2.9.1, and it's working. The problem is in 3.0.0.

**Comment by rpc1910** [comment]
I had the same problem, but I fixed it changing the Node version. Version 3.0.0 require node 14+. My pipeline was using Node 12

**Comment by marco-carvalho** [comment]
@rpc1910 you're right, thanks!
